### ISSUE TITLE
RTC Pi Plus does not work on RBPI2 FreeBSD 11

### ISSUE THREAD

**Issue by sparvu** [vzaigrin/ds1307#1]
I cant make the following device, RTC Pi Plus work on FreeBSD 11 using RBPI2. I compiled your ds1307.c on my FreeBSD 11 arm and tried to run it:

```
root@rpi2:/usr/home/raspberry # ./ds -s -f /dev/iic0
I2CRDWR: Input/output error
I2CRDWR: Input/output error
I2CRDWR: Input/output error
I2CRDWR: Input/output error
I2CRDWR: Input/output error
I2CRDWR: Input/output error
I2CRDWR: Input/output error

root@rpi2:/usr/home/raspberry # ./ds -s -f /dev/iic1
root@rpi2:/usr/home/raspberry # 
```

Here more info from my system:

```
FreeBSD rpi2 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r288098: Thu Aug 20 04:00:38 UTC 2015     root@rpi2:/usr/obj/usr/src/sys/KPI2  arm

root@rpi2:/usr/home/raspberry # dmesg | grep iic
iichb0: <BCM2708/2835 BSC controller> mem 0x205000-0x20501f irq 61 on simplebus0
iicbus0: <OFW I2C bus> on iichb0
iic0: <I2C generic I/O> on iicbus0
iichb1: <BCM2708/2835 BSC controller> mem 0x804000-0x80401f irq 61 on simplebus0
iicbus1: <OFW I2C bus> on iichb1
iic1: <I2C generic I/O> on iicbus1
```

Any ideas how can I make this device work with FreeBSD 11 ?

https://www.abelectronics.co.uk/products/17/Raspberry-Pi--Raspberry-Pi-2-Model-B/52/RTC-Pi-Plus

**Comment by vzaigrin** [comment]
Hello

Did you try to use native DS1307 driver in FreeBSD 11?
The instructions are here: https://vzaigrin.wordpress.com/2015/08/04/real-time-clock-on-raspberry-pi-with-freebsd-11 https://vzaigrin.wordpress.com/2015/08/04/real-time-clock-on-raspberry-pi-with-freebsd-11

Did you try to call my DS1307 utility with read option:

# ds1307 -r -a 0x68 -f /dev/iic1

Did you try to scan iic-bus first?
You can do it by my utility newi2c: https://github.com/vzaigrin/newi2c https://github.com/vzaigrin/newi2c

Best regards,
Vadim Zaigrin

**Comment by sparvu** [comment]
yes, I have been trying to use DS1307 driver from FreeBSD 11. Here some results:

```
# ./newi2c -s -f /dev/iic1
Scanning I2C devices on /dev/iic1: 68 

# ../ds -r -f /dev/iic1
13:28:08 23/08/2015
```

ds is your utility ds1307. I am able to find the device. So next step would be the compile the kernel and install the driver, right ?

**Comment by vzaigrin** [comment]
Yes, see instructions in my post.

**Comment by sparvu** [comment]
This step does not go right: "After that we should to compile and install our new FDT" 
Im using Raspberry PI2, not sure if your instructions work on RBPI2. I did same things as you instructed but Im getting these:

```
root@rpi2:/usr/home/raspberry # dmesg| grep iic
iichb0: <BCM2708/2835 BSC controller> mem 0x205000-0x20501f irq 61 on simplebus0
iicbus0: <OFW I2C bus> on iichb0
iic0: <I2C generic I/O> on iicbus0
iichb1: <BCM2708/2835 BSC controller> mem 0x804000-0x80401f irq 61 on simplebus0
iicbus1: <OFW I2C bus> on iichb1
iic1: <I2C generic I/O> on iicbus1
```

and at the same time

```
root@rpi2:/usr/home/raspberry # ofwdump -a
Node 0x38: 
  Node 0xb4: soc
  Node 0xd8: timer
  Node 0x140: axi
    Node 0x1ac: vc_mem
    Node 0x1d4: interrupt-controller
    Node 0x288: watchdog0
    Node 0x2e8: gpio
      Node 0x410: bsc0_a
      Node 0x448: bsc0_b
      Node 0x480: bsc0_c
      Node 0x4b8: bsc1_a
      Node 0x4f0: bsc1_b
      Node 0x528: gpclk0_a
      Node 0x560: gpclk0_b
      Node 0x598: gpclk0_c
      Node 0x5d0: gpclk0_d
      Node 0x608: gpclk1_a
      Node 0x640: gpclk1_b
      Node 0x678: gpclk1_c
      Node 0x6b0: gpclk1_d
      Node 0x6e8: gpclk2_a
      Node 0x720: gpclk2_b
      Node 0x758: spi0_a
      Node 0x79c: spi0_b
      Node 0x7e0: pwm0_a
      Node 0x814: pwm0_b
      Node 0x848: pwm0_c
      Node 0x87c: pwm1_a
      Node 0x8b0: pwm1_b
      Node 0x8e4: pwm1_c
      Node 0x918: pwm1_d
      Node 0x94c: uart0_a
      Node 0x984: uart0_b
      Node 0x9bc: uart0_c
      Node 0x9f4: uart0_fc_a
      Node 0xa30: uart0_fc_b
      Node 0xa6c: uart0_fc_c
      Node 0xaa8: pcm_a
      Node 0xae8: pcm_b
      Node 0xb28: sm_addr_a
      Node 0xb74: sm_addr_b
      Node 0xbc0: sm_ctl_a
      Node 0xbfc: sm_ctl_b
      Node 0xc38: sm_data_8bit_a
      Node 0xc90: sm_data_8bit_b
      Node 0xce8: sm_data_16bit
      Node 0xd40: sm_data_18bit
      Node 0xd80: bscsl
      Node 0xdb8: spisl
      Node 0xdf8: spi1
      Node 0xe40: uart1_a
      Node 0xe78: uart1_b
      Node 0xeb0: uart1_c
      Node 0xee8: uart1_fc_a
      Node 0xf24: uart1_fc_b
      Node 0xf60: uart1_fc_c
      Node 0xf9c: spi2
      Node 0xfe4: arm_jtag_trst
      Node 0x1020: arm_jtag_a
      Node 0x1068: arm_jtag_b
      Node 0x10b0: reserved
    Node 0x1120: bsc0
    Node 0x119c: bsc1
    Node 0x1218: spi0
    Node 0x1294: dma
    Node 0x1354: mbox
    Node 0x13f0: sdhci
    Node 0x1480: uart0
    Node 0x1534: vchiq
    Node 0x159c: usb
      Node 0x164c: hub
        Node 0x16a4: ethernet
  Node 0x170c: cpus
    Node 0x1738: cpu@0
    Node 0x1794: cpu@1
    Node 0x17f0: cpu@2
    Node 0x184c: cpu@3
  Node 0x18ac: memory
  Node 0x18e4: system
  Node 0x193c: display
  Node 0x19d0: leds
    Node 0x19f4: pwr
    Node 0x1a28: act
  Node 0x1a60: regulator
    Node 0x1b68: regulator@0
    Node 0x1c14: regulator@3
  Node 0x1cc4: aliases
  Node 0x1cec: chosen
```

Im not getting thsi: https://vzaigrin.files.wordpress.com/2015/08/unknown-card1.png

Something is not ok with building FDT table. Right ?

**Comment by vzaigrin** [comment]
For RBPI2 you should change file /usr/src/sys/boot/fdt/dts/arm/bcm2836.dtsi, not bcm2835.dtsi

**Comment by sparvu** [comment]
aha. right. thanks. Got that and edited. Same thing. One additional question: should I build rpi.dtb or rpi2.dtb ?

If I try:

```
root@rpi2:/usr/src/sys/tools/fdt # ./make_dtb.sh /usr/src/sys /usr/src/sys/boot/fdt/dts/arm/rpi2.dts .
converting /usr/src/sys/boot/fdt/dts/arm/rpi2.dts -> /rpi2.dtb
Warning (reg_format): "reg" property in /axi/bsc1/rtc has invalid length (4 bytes) (#address-cells == 2, #size-cells == 1)
Warning (avoid_default_addr_size): Relying on default #address-cells value for /axi/bsc1/rtc
Warning (avoid_default_addr_size): Relying on default #size-cells value for /axi/bsc1/rtc
```

I tried to build the original rpi.dtb using bcm2836.dtsi no go. After booting I dont see anything on iic1 bus.

Any other ideas ?

Many thanks.

**Comment by vzaigrin** [comment]
You should use rpi2.dtb
It’s look like something wrong with your dts files.
How looks the description of bcs1 inside your bcm2836.dtsi?

**Comment by sparvu** [comment]
```
                bsc1 {
                        compatible = "broadcom,bcm2835-bsc",
                                     "broadcom,bcm2708-bsc";
                        reg = <0x804000 0x20>;
                        interrupts = <61>;
                        interrupt-parent = <&intc>;
                        rtc {
                                compatible = "maxim,ds1307";
                                reg = <0xd0>;
                        };
                };
```

Entire file is here: http://www.kronometrix.org/bcm2836.dtsi

**Comment by vzaigrin** [comment]
This looks correct.

But I don't like warnings in the result of make_dtb.sh script.
I don't have such warning on my system.
But I use bcm2835.dtsi, not bcm2836.dtsi
And this files have some differences.
Try to add this to strings after string "bsc1 {"
#address-cells = <1>;
#size-cells = <0>;

So module for bsc1 should looks like this:

```
       bsc1 {
                   #address-cells = <1>;
                   #size-cells = <0>;
                   compatible = "broadcom,bcm2835-bsc",
                                         "broadcom,bcm2708-bsc";
                    reg = <0x804000 0x20>;
                    interrupts = <61>;
                    interrupt-parent = <&intc>;
                    rtc {
                            compatible = "maxim,ds1307";
                            reg = <0xd0>;
                    };
            };
```

Next strange thing is that make_dtb.sh script try to create new file in the root directory (/rpi2.dtb).
It should be in current directory (./rpi2.dtb).
This may happens if you forgot to put '.' as third argument for this script.
Script use it in this way:
dts="$2"
dtb_path=$3
for d in ${dts}; do
     dtb=${dtb_path}/`basename $d .dts`.dtb

Do you get new rpi2.dtb?
Did you compare its size with original rpi2.dtb in /boot/msdos?

**Comment by sparvu** [comment]
bingo. Many thanks indeed. Works nice after adding #address-cells = <1>; and #size-cells = <0>;
I did rebuild the rpi2.dtb current directory, reboot, added the ds1307 driver to the kernel and voila:

```
 % date
Sat Sep 26 23:19:52 EEST 2015

dev.ds1307.0.sqw_out: 0
dev.ds1307.0.sqw_freq: 32768
dev.ds1307.0.sqwe: 0
dev.ds1307.0.%parent: iicbus1
dev.ds1307.0.%pnpinfo: name=rtc compat=maxim,ds1307
dev.ds1307.0.%location: addr=0xd0
dev.ds1307.0.%driver: ds1307
dev.ds1307.0.%desc: Maxim DS1307 RTC
dev.ds1307.%parent: 

```

Maybe you can add some notes about RBPI2 machines and getting DS1307 working.

**Comment by vzaigrin** [comment]
Great!

I am not sure that I can write about RPI2, but I will add a comment to my post about this situation.
